### PR TITLE
Reworked player movement and collision.

### PR DESCRIPTION
**Pull request by avivbiton**
Player will now collide with any gameObjects with the component Collidable on them.
Still want to improve how the movement feel overall, will do that later.

### CODE REVIEW

**Comment by itsfalcon0717** [comment]
Are you using the master branch? The collider 2 branch has all the UI that i worked on!

**Comment by avivbiton** [comment]
No man, I was using the Collider 2 branch, this pull request is requesting to merge into the collider 2 branch not the main branch

**Comment by itsfalcon0717** [comment]
So why is the map gone? Will it be easier if I just gave you push access and add you as a contributor?



Sent from my Bell Samsung device over Canada's largest network.


-------- Original message --------

**Comment by avivbiton** [comment]
I am not sure, which branch did you use for the map? I don't want to ruin some of your progress, all the changes I made is to a few files, so it won't be a problem to add them again. 
Maybe you can try to push all the changes into Collider2 and clean up some of the old branches?

**Comment by avivbiton** [comment]
If you look at the files changes tab, I only changed a few files, your map is probably on a different branch, you just need to merge it into this branch or the main branch

**Comment by itsfalcon0717** [comment]
Ok look at the revert collider revert branch. You should be able to see a map with pallet town created. Again though, should i just give you push access since I am very new to github and that might just make this a lot easier!



Sent from my Bell Samsung device over Canada's largest network.


-------- Original message --------

**Comment by avivbiton** [comment]
You can but I don't want to mess with your repo too much, I will help whenever I can but it still yours and if you are new to github it's a great way to learn.
Anyway, look at this https://github.com/shashankgupta06/Pokemon-Game/compare/collider2...revert-2-collider2

This shows the difference between the branch Collider2 and the revert branch, as you can see the only difference is the changes I made to the player movement. If you are unable to find the map you were working on then you may have selected a wrong branch, Are you using Visual studio Github extension?

**Comment by avivbiton** [comment]
Tell me if you solved the problem you are having with your map.
Since I don't really see it in any of the branches, it could be on your local branch.

**Comment by itsfalcon0717** [comment]
I merged the revert branch and collider2. I cloned collider2, replaced the assets folder from this cloned file to my repo and ran it. The map seems to be intact so check it out. If this does not work i really dont know what the problem is

**Comment by avivbiton** [comment]
Can you send me the link to the file in Github ? (the map file)

**Comment by avivbiton** [comment]
Okay, i figured it out, re-added the player movement update again.

**Pull request merged**
